# Generated by Django 5.0.6 on 2024-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.PositiveSmallIntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'otp code',
                'verbose_name_plural': 'otp code',
            },
        ),
    ]
