# Generated by Django 5.0.6 on 2024-06-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proudct',
            new_name='Prouduct',
        ),
    ]
