# Generated by Django 5.0.6 on 2024-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_prouduct_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prouduct',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='short text'),
        ),
    ]
